#pragma once
#include <string>

namespace Color
{
	typedef enum
	{
		FORECOLOR_BLACK,
		FORECOLOR_DARKBLUE,
		FORECOLOR_DARKGREEN,
		FORECOLOR_DARKCYAN,
		FORECOLOR_DARKRED,
		FORECOLOR_DARKPURPLE,
		FORECOLOR_DARKYELLOW,
		FORECOLOR_LIGHTGRAY,
		FORECOLOR_RESET = 7,
		FORECOLOR_DARKGRAY,
		FORECOLOR_LIGHTBLUE,
		FORECOLOR_LIGHTGREEN,
		FORECOLOR_LIGHTCYAN,
		FORECOLOR_LIGHTRED,
		FORECOLOR_LIGHTPURPLE,
		FORECOLOR_LIGHTYELLOW,
		FORECOLOR_WHITE,
	} ForeColor;

	typedef enum
	{
		BACKCOLOR_RESET,
		BACKCOLOR_BLACK = 0,
		BACKCOLOR_DARKBLUE,
		BACKCOLOR_DARKGREEN,
		BACKCOLOR_DARKCYAN,
		BACKCOLOR_DARKRED,
		BACKCOLOR_DARKPURPLE,
		BACKCOLOR_DARKYELLOW,
		BACKCOLOR_LIGHTGRAY,
		BACKCOLOR_DARKGRAY,
		BACKCOLOR_LIGHTBLUE,
		BACKCOLOR_LIGHTGREEN,
		BACKCOLOR_LIGHTCYAN,
		BACKCOLOR_LIGHTRED,
		BACKCOLOR_LIGHTPURPLE,
		BACKCOLOR_LIGHTYELLOW,
		BACKCOLOR_LIGHTWHITE,
	} BackColor;

	void print(std::string str, ForeColor fcolor = FORECOLOR_RESET, BackColor bcolor = BACKCOLOR_RESET);

	void printcolors(std::string str);
}
